default_context:
  project_name: 'Codegenerator'
  project_slug: 'codegenerator'
  domain_main: 'codegenerator.com'
  domain_staging: 'stag.codegenerator.com'
  docker_swarm_stack_name_main: 'codegenerator-com'
  docker_swarm_stack_name_staging: 'stag-codegenerator-com'
  secret_key: 'Sangeeta11'
  first_superuser: 'Sucharika'
  first_superuser_password: 'Sangeeta11'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.codegenerator.com", "https://stag.codegenerator.com", "https://codegenerator.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@codegenerator.com'
  postgres_password: 'Sangeeta11'
  pgadmin_default_user: 'Sucharika'
  pgadmin_default_user_password: 'Sangeeta11'
  traefik_constraint_tag: 'codegenerator.com'
  traefik_constraint_tag_staging: 'stag.codegenerator.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Sangeeta11'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
